Projeto 1 - Site Institucional
csaraugustol/curso-php-oo pull request #6
Opened 2021-10-06 13:41 UTC by csaraugustol

2021-11-03 14:38 UTC, eduardohenriquesousasilva requested changes
Verificar os comentários adicionados, modificar e responder o comentário, com a correção realizada ou o motivo para não fazer a correção.

Depois disso caso tenha modificado algo, fazer o commit, push e me avisar para olhar o PR novamente

2021-11-03 14:38 UTC, eduardohenriquesousasilva commented on projeto-site-institucional/src/View/View.php
> +     * Caminho da URL
URL ou path? Caso necessário ajustar  o comentário por favor

2021-11-03 17:14 UTC, csaraugustol commented on projeto-site-institucional/src/View/View.php
> +     * Caminho da URL
Path. É o caminho da view para fazer o redirecionamento. Irei fazer a correção.

2021-11-05 12:33 UTC, merged

2021-11-05 13:29 UTC, eduardohenriquesousasilva commented
Remover também todos os console.log que está deixando no meio do código