Projeto 2 - Catálogo de Produtos
csaraugustol/curso-php-oo pull request #7
Opened 2021-10-06 17:54 UTC by csaraugustol

2021-11-03 14:36 UTC, eduardohenriquesousasilva requested changes
Verificar os comentários adicionados, modificar e responder o comentário, com a correção realizada ou o motivo para não fazer a correção.

Dps disso caso tenha modificado algo, fazer o commit, push e me avisar para olhar o PR novamente

2021-11-03 14:36 UTC, eduardohenriquesousasilva commented on projeto-catalogo/src/Entity/Product.php
> +{
Por que essa classe está vazia? Não foi feito no exercício, não falta terminar ela?

2021-11-03 17:11 UTC, csaraugustol commented on projeto-catalogo/src/Entity/Product.php
> +{
Ela é somente uma classe de conexão com o banco. Mas fiz uma adaptação na Product.php adicionando o nome da tabela para que ela não fique vazia. Com isso, também foram feitas alterações na Entity.php.

2021-11-05 12:34 UTC, eduardohenriquesousasilva commented on projeto-catalogo/src/Entity/Product.php
> +{
Ah, sim mas não teria problema ela ficar vazia também apenas perguntei para saber se não estava faltando algo, se não tinha esquecido de implementar ela ou algo assim tranquilo

2021-11-05 12:35 UTC, merged