Projeto 3 - Gerenciador de Gastos Pessoais
csaraugustol/curso-php-oo pull request #8
Opened 2021-10-08 15:55 UTC by csaraugustol

2021-10-21 19:03 UTC, csaraugustol commented on projeto-gerenciador-gastos/src/DataBase/Entity.php
> +        $products = $this->connection->query($findAll);
Mudei os nomes dessas variáveis das linhas 24 e 26

2021-10-21 19:04 UTC, csaraugustol commented on projeto-gerenciador-gastos/src/DataBase/Entity.php
> +    public function insert($data): bool
Adicionar comentário sobre o que o método faz

2021-11-03 14:32 UTC, eduardohenriquesousasilva requested changes
Verificar os comentários adicionados, realizar correções se necessário responder aos comentários quando corrigidos ou com o motivo da não correção deles.

Após isso fazer o commit, push e me avisar para olhar o PR novamente.

2021-11-03 14:32 UTC, eduardohenriquesousasilva commented on projeto-gerenciador-gastos/public/index.php
> + * Realiza a autenticação
Não realiza a autenticação, verifica se está autenticado, favor corrigir o comentário, é importante que o comentário sempre esteja correto de acordo com o que o bloco comentado está fazendo, se ele não estiver correto acaba atrapalhando mais ao invés de ajudar ok?

2021-11-03 14:32 UTC, eduardohenriquesousasilva commented on projeto-gerenciador-gastos/src/View/View.php
> +     * Caminho para URL
Acredito que aqui não queria ser referir a url mas ao path da view correto? Se for isso mesmo ajustar o comentário por favor

2021-11-05 12:36 UTC, merged